services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  student-service:
    build:
      context: ./student-service
    command: node /server.js
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - nginx
    environment:
      RABBITMQ_HOST: rabbitmq

  registration-service:
    build:
      context: ./registration-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - nginx
    environment:
      RABBITMQ_HOST: rabbitmq

  notification-service:
    build:
      context: ./notification-service
    command: node /server.js
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq

  authentication-service:
    build:
      context: ./authentication-service
    command: python run.py
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - nginx
    environment:
      RABBITMQ_HOST: rabbitmq

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
